name: Build Image On Release

on:
  release:
    types: [ published ]
  pull_request:

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/build-image.yml@v6
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "daedalos"
      release_type: "github_commit"
      release_url: "https://api.github.com/repos/DustinBrett/daedalOS/commits/main"
      target-arch: "all"
    secrets:
      scarf_token: ${{ secrets.SCARF_TOKEN }}