name: Build Image On Release

on:
  release:
    types: [ published ]

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/build-image.yml@v4.0.1
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "daedalos"
    secrets:
      scarf_token: ${{ secrets.SCARF_TOKEN }}